name = "Theme"
license = "MIT"
licenselink = "https://github.com/philoserf/theme/blob/master/LICENSE"
description = "A simple and clean blog theme for Hugo"
homepage = "https://github.com/philoserf/theme/"
tags = [
  "personal"
]
features = [
  "favicon",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.79.0"

[author]
name = "Luiz F. A. de Prá"
homepage = "https://luizdepra.com"
